name: "Linux + QT"

inputs:
  backend:
    required: true
    description: "The backend to use (valid: Qt5, Qt6)"

  arch:
    required: true
    description: "The architecture name (e.g aarch64)"

  nativeArch:
    required: true
    description: "The docker architecture to use (e.g arm64)"

  build-type:
    required: true
    description: "The built type (valid: Release, Debug)"

matrix:

runs:
  using: "composite"
  steps:
    - name: 🛸 Checkout Saucer code
      uses: actions/checkout@v4
      with:
        repository: saucer/saucer
        path: saucer
        ref: c-bindings # Temporary.

    - name: 🔥 Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: "linux/${{ inputs.nativeArch }}"

    - name: 📋 Install dependencies & 🔨 Compile
      shell: bash
      run: |
        chmod +x ./build-linux-gnu.sh
        docker run \
          --rm \
          --volume $(pwd):/home/container \
          --workdir /home/container \
          --platform linux/${{ inputs.nativeArch }} \
          "debian:sid-slim" \
          ./build-linux-gnu.sh ${{ inputs.build-type }} ${{ inputs.backend }} ${{ inputs.arch }}

    - name: 📦 Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "Linux-${{ inputs.backend }}-${{ inputs.arch }}-${{ inputs.build-type }}"
        path: "saucer/build/bindings/libsaucer-bindings.so"
