name: "🛸 Compile Saucer"
description: "Installs Dependencies & Compiles Saucer"

inputs:
  backend:
    required: true
    description: The backend to use

  platform:
    required: true
    description: The platform which is used to compile

  build-type:
    required: true
    description: The CMake build configuration

  cmake-args:
    required: false
    description: Additional Arguments passed to cmake

  in-container:
    required: false
    description: Whether or not to run in the current container

  arm-hack:
    required: false
    description: Sets TARGET_ARCH to hack-in support for arm 32bit. Valid inputs arm, armel, armhf

  inline:
    required: false
    default: ""
    description: Sets which modules will get inlined into the main bindings library. Semi-colon separated list. Empty for none.

  static:
    required: false
    default: "OFF"
    description: Inlines all modules and bindings and saucer into a single shared library. NOT RECOMMENDED as it breaks modularity. Set to 'ON' to enable.

runs:
  using: "composite"
  steps:
    - name: Compile (Straight)
      if: inputs.in-container != 'true'
      shell: bash
      run: |
        if [ "${{ inputs.arm-hack }}" == "armel" ]; then
          export TARGET_ARCH="armv6+nofp"
        elif [ "${{ inputs.arm-hack }}" == "armhf" ]; then
          export TARGET_ARCH="armv6+fp"
        elif [ "${{ inputs.arm-hack  }}" == "arm" ]; then
          export TARGET_ARCH="armv5+nofp"
        fi

        cd bindings
        cmake -B build -Dsaucer_backend=${{ inputs.backend }} -Dsaucer_bindings_inline_modules="${{ inputs.inline }}" -Dsaucer_bindings_static=${{ inputs.static }} ${{ inputs.cmake-args }}
        cmake --build build --config ${{ inputs.build-type }}

    - name: Compile (In-Container)
      if: inputs.in-container == 'true'
      uses: ./.github/actions/run-in-container
      with:
        command: |
          if [ "${{ inputs.arm-hack }}" == "armel" ]; then
            export TARGET_ARCH="armv6+nofp"
          elif [ "${{ inputs.arm-hack }}" == "armhf" ]; then
            export TARGET_ARCH="armv6+fp"
          elif [ "${{ inputs.arm-hack  }}" == "arm" ]; then
            export TARGET_ARCH="armv5+nofp"
          fi

          cd bindings
          cmake -B build -Dsaucer_backend=${{ inputs.backend }} -Dsaucer_bindings_inline_modules="${{ inputs.inline }}" -Dsaucer_bindings_static=${{ inputs.static }} ${{ inputs.cmake-args }}
          cmake --build build --config ${{ inputs.build-type }}
