on:
  push:
  pull_request:

name: ⛓️ Build C Bindings (Windows + WebView2)

jobs:
  build-windows-msvc:
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Release
          - Debug
        platform:
          # - { arch: x86, nativeArch: x86 }
          - { arch: x86_64, nativeArch: x64 }

    runs-on: windows-latest
    name: "Windows-WebView2-${{ matrix.platform.arch }}-${{ matrix.build-type }}"

    # env:
    #   TARGET_ARCH: ${{ matrix.platform.nativeArch }}
    steps:
      - name: 📥 Checkout actions code
        uses: actions/checkout@v4

      - name: 🛸 Checkout Saucer bindings code
        uses: actions/checkout@v4
        with:
          repository: saucer/bindings
          path: saucer
          ref: main

      - name: 🔨 Compile
        shell: cmd
        run: |
          cd saucer
          mkdir build 
          cd build
          cmake .. -B build -Dsaucer_msvc_hack=ON -Dsaucer_backend=WebView2
          cmake --build build . --config ${{ matrix.build-type }}

      - name: 📦 Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Windows-WebView2-${{ matrix.platform.arch }}-${{ matrix.build-type }}"
          path: "saucer/build/bindings/${{ matrix.build-type }}/**"
