on:
  push:
  pull_request:

name: ⚠️ GNU/Linux + Qt6 EXPERIMENTAL

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true # Shut up. https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

jobs:
  experimental-build-gnu_linux-qt6:
    strategy:
      fail-fast: false
      matrix:
        build-type:
          # - Release
          - Debug
        platform:
          # Check these for architecture compatibility:
          # https://packages.debian.org/search?searchon=names&keywords=qt6-webengine-dev
          # https://hub.docker.com/_/debian/tags?page=&page_size=&ordering=&name=sid-slim
          # https://github.com/tonistiigi/binfmt?tab=readme-ov-file#build-test-image
          # - {
          #     # Not working at the moment, TODO
          #     arch: "x86",
          #     qemuArch: "linux/386",
          #     dockerArch: SAME_AS_QEMU,
          #   }
          - {
              #
              arch: "aarch64",
              qemuArch: "linux/arm64/v8",
              dockerArch: SAME_AS_QEMU,
            }

    runs-on: ubuntu-latest
    name: "EXPERIMENTAL-GNU_Linux-Qt6-${{ matrix.platform.arch }}-${{ matrix.build-type }}"

    steps:
      - name: 📥 Checkout actions code
        uses: actions/checkout@v4

      - name: 🛸 Checkout Saucer bindings code
        uses: actions/checkout@v4
        with:
          repository: saucer/bindings
          path: saucer
          ref: main

      - name: 👨‍💻 Setup container
        uses: ./.github/actions/setup-container
        with:
          qemuArch: ${{ matrix.platform.qemuArch }}
          dockerArch: ${{ matrix.platform.dockerArch }}
          image: "debian:sid-slim"

      - name: 📋 Install dependencies
        uses: ./.github/actions/run-in-container
        with:
          command: |
            apt update
            apt install -y build-essential git gcc-14 cmake xvfb

      - name: 📋 Install Qt6 dependencies
        uses: ./.github/actions/run-in-container
        with:
          command: |
            apt install -y qt6-base-dev qt6-tools-dev qt6-declarative-dev qt6-webchannel-dev qt6-webengine-dev qt6-svg-dev

      - name: 🔨 Compile
        uses: ./.github/actions/run-in-container
        with:
          command: |
            if [ "${{ matrix.platform.arch }}" == "armel" ]; then
              export TARGET_ARCH="armv6+nofp"
            elif [ "${{ matrix.platform.arch }}" == "armhf" ]; then
              export TARGET_ARCH="armv6+fp"
            fi

            cd saucer
            cmake -B build -Dsaucer_backend=Qt6
            cmake --build build --config ${{ matrix.build-type }}

      - name: 📦 Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "GNU_Linux-Qt6-${{ matrix.platform.arch }}-${{ matrix.build-type }}"
          path: "saucer/build/libsaucer-bindings.so"
